name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y php7.4-cli php7.4-zip unzip
        curl -sS <https://getcomposer.org/installer> | php
        sudo mv composer.phar /usr/local/bin/composer
        composer install
				

    - name: Deploy code
      uses: easingthemes/ssh-deploy@v2.0.6
      with:
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        args: "-rltgoDzvO --delete"
        local_path: "."
        server: ${{ secrets.SERVER }}
        remote_path: "/var/www/html"
 
    - name: Notify Slack
      if: always()
      uses: rtCamp/action-slack-notify@v2.1.1
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: '#practical-test'
      with:
        status: ${{ job.status }}
        fields: repo,commit,actor,job,status,steps,run_number
        custom_payload: |
          {
            "attachments": [
              {
                "fallback": "Deployment ${{ job.status }}",
                "color": "#36a64f",
                "title": "Deployment ${{ job.status }}",
                "text": "Deployment of the latest code to production is ${{ job.status }}.",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  {
                    "title": "Commit",
                    "value": "${{ github.sha }}",
                    "short": true
                  },
                  {
                    "title": "Actor",
                    "value": "${{ github.actor }}",
                    "short": true
                  },
                  {
                    "title": "Job",
                    "value": "${{ job.name }}",
                    "short": true
                  },
                  {
                    "title": "Status",
                    "value": "${{ job.status }}",
                    "short": true
                  },
                  {
                    "title": "Steps",
                    "value": "${{ job.steps }}",
                    "short": false
                  },
                  {
                    "title": "Run Number",
                    "value": "${{ github.run_number }}",
                    "short": true
                  }
                ]
              }
            ]
          }
        env: ${{ toJson(env) }}
        secrets: ${{ toJson(secrets) }} 
